language: cpp
os: linux
compiler:
  - gcc
  - clang
env:
  - GCC_VERSION=4.7 RUN_TEST=buildonly
  - GCC_VERSION=4.7 RUN_TEST=world
  - GCC_VERSION=4.7 RUN_TEST=tensor
  - GCC_VERSION=4.7 RUN_TEST=mra
  - GCC_VERSION=4.8 RUN_TEST=buildonly
  - GCC_VERSION=4.8 RUN_TEST=world
  - GCC_VERSION=4.8 RUN_TEST=tensor
  - GCC_VERSION=4.8 RUN_TEST=mra
  - GCC_VERSION=4.9 RUN_TEST=buildonly
  - GCC_VERSION=4.9 RUN_TEST=world
  - GCC_VERSION=4.9 RUN_TEST=tensor
  - GCC_VERSION=4.9 RUN_TEST=mra
matrix:
  exclude:
    - compiler: clang
      env: GCC_VERSION=4.7 RUN_TEST=buildonly
    - compiler: clang
      env: GCC_VERSION=4.7 RUN_TEST=world
    - compiler: clang
      env: GCC_VERSION=4.7 RUN_TEST=tensor
    - compiler: clang
      env: GCC_VERSION=4.7 RUN_TEST=mra
    - compiler: clang
      env: GCC_VERSION=4.9 RUN_TEST=buildonly
    - compiler: clang
      env: GCC_VERSION=4.9 RUN_TEST=world
    - compiler: clang
      env: GCC_VERSION=4.9 RUN_TEST=tensor
    - compiler: clang
      env: GCC_VERSION=4.9 RUN_TEST=mra
#notifications:
#  email:
#    recipients:
#      - madness-developers@googlegroups.com
#    on_success: change
#    on_failure: always
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - gcc-$GCC_VERSION
      - g++-$GCC_VERSION
      - gfortran-$GCC_VERSION
      - libblas-dev
      - liblapack-dev
      - libgoogle-perftools-dev
      - mpich2
      - libtbb-dev
      - cmake

before_install: ./ci/dep-$TRAVIS_OS_NAME.sh
script: ./ci/build-$TRAVIS_OS_NAME.sh
after_failure: cat ./config.log