language: cpp
os:
  - osx
  - linux
compiler:
  - clang
  - gcc
env:
  - GCC_VERSION=4.7 RUN_TEST=buildonly
  - GCC_VERSION=4.8 RUN_TEST=buildonly
  - GCC_VERSION=4.9 RUN_TEST=buildonly
#  - GCC_VERSION=4.7 RUN_TEST=world
#  - GCC_VERSION=4.8 RUN_TEST=world
#  - GCC_VERSION=4.9 RUN_TEST=world
#  - GCC_VERSION=4.7 RUN_TEST=tensor
#  - GCC_VERSION=4.8 RUN_TEST=tensor
#  - GCC_VERSION=4.9 RUN_TEST=tensor
#  - GCC_VERSION=4.7 RUN_TEST=mra
#  - GCC_VERSION=4.8 RUN_TEST=mra
#  - GCC_VERSION=4.9 RUN_TEST=mra
matrix:
  # We will not count Mac failures until the issues with the
  # Travis build are resolved.
  allow_failures:
    - os: osx
  exclude:
    - compiler: clang
      env: GCC_VERSION=4.7 RUN_TEST=buildonly
    - compiler: clang
      env: GCC_VERSION=4.8 RUN_TEST=buildonly
    - compiler: clang
      env: GCC_VERSION=4.7 RUN_TEST=world
    - compiler: clang
      env: GCC_VERSION=4.8 RUN_TEST=world
    - compiler: clang
      env: GCC_VERSION=4.7 RUN_TEST=tensor
    - compiler: clang
      env: GCC_VERSION=4.8 RUN_TEST=tensor
    - compiler: clang
      env: GCC_VERSION=4.7 RUN_TEST=mra
    - compiler: clang
      env: GCC_VERSION=4.8 RUN_TEST=mra
    - os: osx
      compiler: gcc
#notifications:
#  email:
#    recipients:
#      - madness-developers@googlegroups.com
#    on_success: change
#    on_failure: always
sudo: false
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - gcc-4.7
      - g++-4.7
      - gfortran-4.7
      - gcc-4.8
      - g++-4.8
      - gfortran-4.8
      - gcc-4.9
      - g++-4.9
      - gfortran-4.9
      - gcc-5
      - g++-5
      - gfortran-5
      - clang-3.6
      - libc++-dev
      - libc++1
      # BLAS/LAPACK libraries - use OpenBLAS or ATLAS if faster...
      - libblas-dev
      - liblapack-dev
      - libopenblas-base
      #- libatlas3-base # "E: Unable to locate package libatlas3-base"
      # END
      - libgoogle-perftools-dev
      #- mpich2 # disallowed - build from source
      - libtbb-dev
      #- cmake
# if necessary to debug the install step, move all lines into
# script step and add appropriate debugging analysis to the
# after_failure step e.g. find . -name config.log -exec cat {} ";"
install:
  - ./ci/dep-$TRAVIS_OS_NAME.sh
script:
  - ./ci/build-$TRAVIS_OS_NAME.sh
after_failure:
  - cat ./build/config.log
